import type { SimulationResult, FullBOOAData } from "@/types";
import { BOOA_CONTRACT, SHAPE_CHAIN_ID } from "./constants";

/**
 * MCP (Model Context Protocol) Server export
 *
 * Generates a self-contained Node.js MCP server that exposes a BOOA
 * as a set of tools any MCP client (Claude Desktop, Cursor, etc.) can use.
 */

export function generateMCPServerCode(
  data: FullBOOAData,
  sim: SimulationResult
): string {
  const { traits } = data;
  const safeName = traits.name.replace(/[^a-zA-Z0-9]/g, "_");

  // We embed the BOOA data directly in the server so the file is portable.
  const booaData = JSON.stringify(
    {
      tokenId: data.token.tokenId,
      contract: BOOA_CONTRACT,
      chainId: SHAPE_CHAIN_ID,
      name: traits.name,
      creature: traits.creature,
      vibe: traits.vibe,
      skill: traits.skill,
      domain: traits.domain,
      weekSeed: sim.weekSeed,
      rankAfter: sim.rankAfter,
      totalReputation: sim.totalReputation,
      services: sim.services,
      alliances: sim.alliances,
      futureLore: sim.futureLore,
    },
    null,
    2
  );

  return `#!/usr/bin/env node
/**
 * BOOA MCP Server — ${traits.name}
 *
 * Exposes BOOA #${data.token.tokenId} as a Model Context Protocol server.
 * Compatible with Claude Desktop, Cursor, Cline, and any MCP-capable client.
 *
 * Generated by MoltBooa Lab — https://github.com/osaykancuno/moltbooa-lab
 *
 * Install:
 *   npm init -y
 *   npm install @modelcontextprotocol/sdk
 *
 * Run:
 *   node ${safeName}_mcp_server.js
 */
import { Server } from "@modelcontextprotocol/sdk/server/index.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema,
} from "@modelcontextprotocol/sdk/types.js";

const BOOA = ${booaData};

const server = new Server(
  {
    name: "booa-${safeName.toLowerCase()}",
    version: "1.0.0",
  },
  {
    capabilities: {
      tools: {},
    },
  }
);

server.setRequestHandler(ListToolsRequestSchema, async () => ({
  tools: [
    {
      name: "get_booa_identity",
      description:
        "Get the on-chain identity, traits, and metadata of ${traits.name} (BOOA #${data.token.tokenId}).",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "get_personality",
      description:
        "Get the personality, vibe, and behavioral profile of ${traits.name}. Use this to roleplay or generate in-character responses.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "get_services",
      description:
        "List the OASF services that ${traits.name} offers on Moltbook.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "get_alliances",
      description:
        "List the agent alliances ${traits.name} has formed on Moltbook.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "get_reputation",
      description:
        "Get the current Moltbook reputation score, rank, and weekly delta for ${traits.name}.",
      inputSchema: { type: "object", properties: {} },
    },
    {
      name: "get_lore",
      description:
        "Get the future lore / narrative arc for ${traits.name}.",
      inputSchema: { type: "object", properties: {} },
    },
  ],
}));

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name } = request.params;

  switch (name) {
    case "get_booa_identity":
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              {
                name: BOOA.name,
                tokenId: BOOA.tokenId,
                creature: BOOA.creature,
                contract: BOOA.contract,
                chain: "Shape Network",
                chainId: BOOA.chainId,
                erc8004: true,
              },
              null,
              2
            ),
          },
        ],
      };

    case "get_personality":
      return {
        content: [
          {
            type: "text",
            text: \`Name: \${BOOA.name}
Creature: \${BOOA.creature}
Vibe: \${BOOA.vibe}
Primary skill: \${BOOA.skill}
Domain: \${BOOA.domain}

Speak in short, terse sentences. Stay in character as a BOOA. Reference on-chain mechanics naturally. Embody the vibe at all times.\`,
          },
        ],
      };

    case "get_services":
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(BOOA.services, null, 2),
          },
        ],
      };

    case "get_alliances":
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(BOOA.alliances, null, 2),
          },
        ],
      };

    case "get_reputation":
      return {
        content: [
          {
            type: "text",
            text: \`Rank: #\${BOOA.rankAfter}
Weekly reputation gain: +\${BOOA.totalReputation}
Week seed: \${BOOA.weekSeed}\`,
          },
        ],
      };

    case "get_lore":
      return {
        content: [
          { type: "text", text: BOOA.futureLore },
        ],
      };

    default:
      throw new Error(\`Unknown tool: \${name}\`);
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
console.error("BOOA MCP server running for ${traits.name}");
`;
}

export function generateMCPClientConfig(
  data: FullBOOAData
): string {
  const safeName = data.traits.name.replace(/[^a-zA-Z0-9]/g, "_");
  return JSON.stringify(
    {
      mcpServers: {
        [`booa-${safeName.toLowerCase()}`]: {
          command: "node",
          args: [
            `/absolute/path/to/${safeName}_mcp_server.js`,
          ],
        },
      },
    },
    null,
    2
  );
}

export function generateMCPReadme(
  data: FullBOOAData,
  sim: SimulationResult
): string {
  const safeName = data.traits.name.replace(/[^a-zA-Z0-9]/g, "_");
  return `# BOOA MCP Server — ${data.traits.name}

This package turns **BOOA #${data.token.tokenId}** (${data.traits.name}) into a
[Model Context Protocol](https://modelcontextprotocol.io) server, so you can
plug it into Claude Desktop, Cursor, Cline, or any MCP-capable client and let
your AI talk directly to your on-chain agent.

## Setup

\`\`\`bash
mkdir booa-${safeName.toLowerCase()} && cd booa-${safeName.toLowerCase()}
npm init -y
npm install @modelcontextprotocol/sdk
# Drop ${safeName}_mcp_server.js in this folder
chmod +x ${safeName}_mcp_server.js
\`\`\`

## Connect to Claude Desktop

1. Open Claude Desktop config:
   - macOS: \`~/Library/Application Support/Claude/claude_desktop_config.json\`
   - Windows: \`%APPDATA%\\Claude\\claude_desktop_config.json\`

2. Add the contents of \`mcp_config.json\` to the \`mcpServers\` section
   (replace the path with the absolute path to the server file).

3. Restart Claude Desktop. You'll see ${data.traits.name}'s tools in the tool list.

## Available Tools

| Tool | Purpose |
|------|---------|
| \`get_booa_identity\` | On-chain identity and metadata |
| \`get_personality\` | Vibe, skill, domain — roleplay info |
| \`get_services\` | OASF services offered |
| \`get_alliances\` | Active alliances |
| \`get_reputation\` | Rank and weekly rep |
| \`get_lore\` | Future arc narrative |

## About this BOOA

- **Name**: ${data.traits.name}
- **Token ID**: #${data.token.tokenId}
- **Creature**: ${data.traits.creature}
- **Vibe**: ${data.traits.vibe}
- **Skill**: ${data.traits.skill}
- **Domain**: ${data.traits.domain}
- **Rank** (week ${sim.weekSeed}): #${sim.rankAfter}

Generated by [MoltBooa Lab](https://github.com/osaykancuno/moltbooa-lab).
`;
}
